<?php

namespace AppBundle\Repository;

/**
 * CreerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreerRepository extends \Doctrine\ORM\EntityRepository
{
}
