<?php

namespace AppBundle\Repository;

/**
 * PateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PateRepository extends \Doctrine\ORM\EntityRepository
{
}
