<?php

namespace AppBundle\Repository;

/**
 * PersonnesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonnesRepository extends \Doctrine\ORM\EntityRepository
{
}
